version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      NESTED_MODULES: ""
      API_DIRS: "{{.ROOT_DIR}}/api/..."
      MANIFEST_OUT: "{{.ROOT_DIR}}/api/crds/manifests"
      CODE_DIRS: "{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/..."
      COMPONENTS: "usage-operator"
      REPO_URL: "https://github.com/openmcp-project/usage-operator"
      GENERATE_DOCS_INDEX: "true"
      CHART_COMPONENTS: "[]"
      ENVTEST_REQUIRED: "true"
