version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    vars:
      NESTED_MODULES: ""
      API_DIRS: "{{.ROOT_DIR}}/api/..."
      MANIFEST_OUT: "{{.ROOT_DIR}}/api/crds/manifests"
      CODE_DIRS: "{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/..."
      COMPONENTS: "usage-operator"
      REPO_URL: "https://github.com/openmcp-project/usage-operator"
      GENERATE_DOCS_INDEX: "true"
      CHART_COMPONENTS: "[]"
      ENVTEST_REQUIRED: "true"

tasks:
  platformservice:
    desc: "  Generates a PlatformService manifest for the current version. Set the VERBOSITY env var to overwrite the default verbosity level (INFO)."
    requires:
      vars:
      - VERSION
    vars:
      VERBOSITY:
        sh: echo "${VERBOSITY:-INFO}"
    cmds:
    - cmd: |
        cat << EOF
        apiVersion: openmcp.cloud/v1alpha1
        kind: PlatformService
        metadata:
          name: usage
        spec:
          image: ghcr.io/openmcp-project/images/usage-operator:{{.VERSION}}
          verbosity: {{.VERBOSITY}}
        EOF
      silent: true
