---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.openmcp.cloud
  resources:
  - managedcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openmcp.cloud
  resources:
  - managedcontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - core.openmcp.cloud
  resources:
  - managedcontrolplanes/status
  verbs:
  - get
  - patch
  - update
