//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyUsage) DeepCopyInto(out *DailyUsage) {
	*out = *in
	in.Date.DeepCopyInto(&out.Date)
	out.Usage = in.Usage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyUsage.
func (in *DailyUsage) DeepCopy() *DailyUsage {
	if in == nil {
		return nil
	}
	out := new(DailyUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUsage) DeepCopyInto(out *MCPUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUsage.
func (in *MCPUsage) DeepCopy() *MCPUsage {
	if in == nil {
		return nil
	}
	out := new(MCPUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUsageList) DeepCopyInto(out *MCPUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUsageList.
func (in *MCPUsageList) DeepCopy() *MCPUsageList {
	if in == nil {
		return nil
	}
	out := new(MCPUsageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUsageSpec) DeepCopyInto(out *MCPUsageSpec) {
	*out = *in
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = make([]DailyUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUsageCaptured.DeepCopyInto(&out.LastUsageCaptured)
	in.MCPCreatedAt.DeepCopyInto(&out.MCPCreatedAt)
	in.MCPDeletedAt.DeepCopyInto(&out.MCPDeletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUsageSpec.
func (in *MCPUsageSpec) DeepCopy() *MCPUsageSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUsageStatus) DeepCopyInto(out *MCPUsageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUsageStatus.
func (in *MCPUsageStatus) DeepCopy() *MCPUsageStatus {
	if in == nil {
		return nil
	}
	out := new(MCPUsageStatus)
	in.DeepCopyInto(out)
	return out
}
