name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@25cc8d1c795127087fa7f26b278b23ae8b35478a # main
    secrets: inherit
