name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@dcab75e52b34789ede669947300504d208d06ae3 # main
    secrets: inherit
