name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@25cc8d1c795127087fa7f26b278b23ae8b35478a # main
    secrets: inherit
