name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@04e9a1153743bd02ab08fc3bb772cb98a5cf1edd # main
    secrets: inherit
