name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    uses: openmcp-project/build/.github/workflows/release.lib.yaml@04e9a1153743bd02ab08fc3bb772cb98a5cf1edd # main
    secrets: inherit
