name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    uses: openmcp-project/build/.github/workflows/release.lib.yaml@b502e7a3478ba1944abb4a69aea548d115721e96 # main
    secrets: inherit
