name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@9f558681b696ebc1818c93d0dbaee66bca26779c # main
    secrets: inherit
