name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@c2d37b930a47b3596b919583887f92c7e37987e3 # main
    secrets: inherit
