name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@ca63f82696e8311fa8494cfa59221a58f1787e59 # main
    secrets: inherit
