name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@ca63f82696e8311fa8494cfa59221a58f1787e59 # main
    secrets: inherit
