name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@c2d37b930a47b3596b919583887f92c7e37987e3 # main
    secrets: inherit
